name: Test images

on:
  pull_request:
    branches:
      - master
jobs:
  test0:
    name: Test images with 0 needs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
      - name: export file changes
        run: export CHANGED_FILES="${{ steps.get_file_changes.outputs.files }}"
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - run: python3 -m pip install ruamel.yaml
      - name: Push to docker registry
        run: |
          python3 ./Build.py build needs 0
        env:
          CHANGED_FILES: "${{ steps.get_file_changes.outputs.files }}"

  test1:
    name: Test images with 1 needs
    runs-on: ubuntu-latest
    needs: [test0]
    steps:
      - uses: actions/checkout@master
      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
      - name: export file changes
        run: export CHANGED_FILES="${{ steps.get_file_changes.outputs.files }}"
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - run: python3 -m pip install ruamel.yaml
      - name: Push to docker registry
        run: |
          python3 ./Build.py build needs 1
        env:
          CHANGED_FILES: "${{ steps.get_file_changes.outputs.files }}"

  test2:
    name: Test images with 2 needs
    runs-on: ubuntu-latest
    needs: [test0, test1]
    steps:
      - uses: actions/checkout@master
      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
      - name: export file changes
        run: export CHANGED_FILES="${{ steps.get_file_changes.outputs.files }}"
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - run: python3 -m pip install ruamel.yaml
      - name: Push to docker registry
        run: |
          python3 ./Build.py build needs 2
        env:
          CHANGED_FILES: "${{ steps.get_file_changes.outputs.files }}"

#  test3:
#    name: Test images with 3 needs
#    runs-on: ubuntu-latest
#    needs: [test0, test1, test2]
#    steps:
#      - uses: actions/checkout@master
#      - name: Get file changes
#        id: get_file_changes
#        uses: dorner/file-changes-action@v1.2.0
#        with:
#          githubToken: ${{ secrets.GITHUB_TOKEN }}
#          plaintext: true
#      - name: export file changes
#        run: export CHANGED_FILES="${{ steps.get_file_changes.outputs.files }}"
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: crazy-max/ghaction-docker-buildx@v1
#        with:
#          version: latest
#      - run: python3 -m pip install ruamel.yaml
#      - name: Push to docker registry
#        run: |
#          python3 ./Build.py build needs 3
#        env:
#          CHANGED_FILES: "${{ steps.get_file_changes.outputs.files }}"
#
#  test4:
#    name: Test images with 4 needs
#    runs-on: ubuntu-latest
#    needs: [test0, test1, test2, test3]
#    steps:
#      - uses: actions/checkout@master
#      - name: Get file changes
#        id: get_file_changes
#        uses: dorner/file-changes-action@v1.2.0
#        with:
#          githubToken: ${{ secrets.GITHUB_TOKEN }}
#          plaintext: true
#      - name: export file changes
#        run: export CHANGED_FILES="${{ steps.get_file_changes.outputs.files }}"
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: crazy-max/ghaction-docker-buildx@v1
#        with:
#          version: latest
#      - run: python3 -m pip install ruamel.yaml
#      - name: Push to docker registry
#        run: |
#          python3 ./Build.py build needs 1
#        env:
#          CHANGED_FILES: "${{ steps.get_file_changes.outputs.files }}"