name: â« Update everything

on:
  schedule:
    - cron:  '40 16 * * *'

jobs:
  deploy:
    name: Update everything
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create git config
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'actions@users.noreply.github.com'

      - name: Update everything
        run: |
            make requirements
            make update
            make documentation

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: timestamp
          reviewers: ludeeus
          title: "Updates pending ğŸ‰"
          body: "<!-- hidden message: Tagging @ludeeus so he get a notification -->"